return {
  { import = "plugins.tabout" },
  { import = "plugins.luasnip" },
  { import = "plugins.conform" },
  { import = "plugins.tmux-navigator" },
  { import = "plugins.mason-lspconfig" },
  { import = "plugins.none-ls" },
  { import = "plugins.prettier" },
  { import = "plugins.lspconfig" },
  { import = "plugins.typescript-tools" },
  { import = "plugins.nvimtree" },
  { import = "plugins.comment" },
  { import = "plugins.harpoon" },
  { import = "plugins.treesitter" },
  { import = "plugins.treesitter-textobjects" },
  { import = "plugins.sleuth" },
  { import = "plugins.treesj" },
  { import = "plugins.oil" },
  { import = "plugins.ts-error-translator" },
  { import = "plugins.grug-far" },
  { import = "plugins.trouble" },
  { import = "plugins.diffview" },
  { import = "plugins.avante" },
  { "folke/which-key.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
}
